# Generated by Django 2.0.3 on 2018-05-16 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company_branch', '0005_auto_20180509_1743'),
        ('purchase_order', '0007_auto_20180515_1906'),
        ('purchaseorggroup', '0003_auto_20180509_1712'),
        ('company', '0008_auto_20180514_1542'),
        ('material_master', '0002_material_is_sales'),
        ('vendor', '0003_auto_20180515_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_no', models.CharField(max_length=150)),
                ('vehicle_no', models.CharField(max_length=150)),
                ('check_post', models.CharField(max_length=255)),
                ('challan_no', models.CharField(max_length=150)),
                ('challan_date', models.DateTimeField()),
                ('is_approve', models.CharField(choices=[('2', 'False'), ('1', 'True'), ('0', 'None')], default='0', max_length=1)),
                ('is_finalised', models.CharField(choices=[('2', 'False'), ('1', 'True'), ('0', 'None')], default='0', max_length=1)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('po_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_order.PurchaseOrder')),
                ('pur_grp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchaseorggroup.PurchaseGroup')),
                ('pur_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchaseorggroup.PurchaseOrg')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.Vendor')),
                ('vendor_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.VendorAddress')),
            ],
        ),
        migrations.CreateModel(
            name='GRNDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('receive_quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('company_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_branch.CompanyBranch')),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grn_detail', to='purchase_order.PurchaseOrder')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_master.Material')),
                ('storage_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_branch.StorageBin')),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_branch.StorageLocation')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_branch.UOM')),
            ],
        ),
        migrations.CreateModel(
            name='GRNMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_no', models.CharField(max_length=255)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grn_map', to='purchase_order.PurchaseOrder')),
            ],
        ),
    ]
