# Generated by Django 2.0.5 on 2018-06-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reversgrn',
            name='revers_gen_no',
            field=models.CharField(default='2018-06-07/REGRN-001', max_length=255),
            preserve_default=False,
        ),
    ]
