# Generated by Django 2.0.5 on 2018-06-09 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grndetail',
            name='uom',
        ),
    ]
