# Generated by Django 2.0.3 on 2018-05-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grn',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
