# Generated by Django 2.0.5 on 2018-06-07 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grn', '0002_auto_20180607_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReversGRN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reverse_quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('is_approve', models.CharField(choices=[('2', 'False'), ('1', 'True'), ('0', 'None')], default='0', max_length=1)),
                ('is_finalised', models.CharField(choices=[('2', 'False'), ('1', 'True'), ('0', 'None')], default='0', max_length=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grn.GRN')),
            ],
        ),
    ]
