# Generated by Django 2.0.3 on 2018-05-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0002_auto_20180516_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
