# Generated by Django 2.0.5 on 2018-06-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0002_remove_grndetail_uom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grn',
            name='project',
        ),
    ]
