# Generated by Django 2.0.3 on 2018-05-16 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0003_auto_20180516_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grndetail',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grn_detail', to='grn.GRN'),
        ),
        migrations.AlterField(
            model_name='grnmap',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grn_map', to='grn.GRN'),
        ),
    ]
