# Generated by Django 2.0.5 on 2018-06-20 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material_master', '0001_initial'),
        ('grn', '0003_remove_grn_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReverseGRNDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reverse_grn_quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_master.Material')),
            ],
        ),
        migrations.RemoveField(
            model_name='reversgrn',
            name='reverse_quantity',
        ),
        migrations.AddField(
            model_name='reversegrndetail',
            name='reverse_grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_grn_detail', to='grn.ReversGRN'),
        ),
    ]
