# Generated by Django 2.0.3 on 2018-05-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0004_auto_20180516_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
