# Generated by Django 2.0.5 on 2018-06-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0004_auto_20180620_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='approval_level',
            field=models.IntegerField(default='0'),
        ),
    ]
