# Generated by Django 2.0.5 on 2018-06-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0005_grn_approval_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='reversgrn',
            name='approval_level',
            field=models.IntegerField(default='0'),
        ),
    ]
