# Generated by Django 2.0.5 on 2018-06-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0006_reversgrn_approval_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reversgrn',
            name='reverse_reason',
        ),
        migrations.AddField(
            model_name='reversegrndetail',
            name='reverse_reason',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
