# Generated by Django 2.0.5 on 2018-06-11 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockissue',
            name='stock',
        ),
        migrations.AddField(
            model_name='stockissue',
            name='stockview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.StockView'),
        ),
    ]
