# Generated by Django 2.0.5 on 2018-06-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20180611_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockissue',
            name='issue_type',
            field=models.CharField(choices=[('2', 'OnProject'), ('1', 'OutProject'), ('0', 'None')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='stockissue',
            name='transfer_type',
            field=models.CharField(choices=[('3', 'Freeable'), ('2', 'Chargeable'), ('1', 'Returnable'), ('0', 'None')], default='0', max_length=1),
        ),
    ]
