# Generated by Django 2.0.5 on 2018-06-07 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gstrates', '0001_initial'),
        ('material_master', '0005_auto_20180607_1244'),
        ('purchase_requisition', '0001_initial'),
        ('company', '0001_initial'),
        ('vendor', '0001_initial'),
        ('uom', '0001_initial'),
        ('company_project', '0002_auto_20180607_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_no', models.CharField(max_length=255)),
                ('quotation_no', models.CharField(max_length=200)),
                ('quotation_date', models.DateTimeField()),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('grand_total_words', models.CharField(max_length=255)),
                ('is_approve', models.CharField(choices=[('2', 'False'), ('1', 'True'), ('0', 'None')], default='0', max_length=1)),
                ('is_finalised', models.CharField(choices=[('2', 'False'), ('1', 'True'), ('0', 'None')], default='0', max_length=1)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_project.CompanyProject')),
                ('requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_requisition.Requisition')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.Vendor')),
                ('vendor_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.VendorAddress')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('order_quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('material_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('igst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_date', models.DateTimeField()),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_master.Material')),
                ('material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_master.MaterialType')),
                ('po_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_detail', to='purchase_order.PurchaseOrder')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uom.UOM')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderFreight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freight_option', models.CharField(blank=True, choices=[('1', 'Vendor'), ('2', 'Own')], default=None, max_length=1, null=True)),
                ('freight_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('freight_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('freight_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('freight_gst_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gstrates.GSTrates')),
                ('po_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_freight', to='purchase_order.PurchaseOrder')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_terms', to='purchase_order.PurchaseOrder')),
                ('po_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.TermsandConditon')),
            ],
        ),
    ]
