# Generated by Django 2.0.5 on 2018-06-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='project',
        ),
    ]
