# Generated by Django 2.0.5 on 2018-06-12 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_remove_purchaseorder_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderdetail',
            name='material_type',
        ),
    ]
