# Generated by Django 2.0.5 on 2018-06-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0004_purchaseorderdetail_avail_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='approval_level',
            field=models.IntegerField(default='0'),
        ),
    ]
