# Generated by Django 2.0.5 on 2018-06-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='po_order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='po_order_no',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='purchase_inv_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='purchase_inv_no',
        ),
    ]
