# Generated by Django 2.0.5 on 2018-06-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20180609_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='vendor_address',
        ),
    ]
