# Generated by Django 2.0.5 on 2018-06-16 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appapprovepermission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpApproveDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_level', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='empapprove',
            name='emp_level',
        ),
        migrations.RemoveField(
            model_name='empapprove',
            name='primary_emp',
        ),
        migrations.RemoveField(
            model_name='empapprove',
            name='secondary_emp',
        ),
        migrations.AddField(
            model_name='empapprovedetail',
            name='emp_approve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appapprovepermission.EmpApprove'),
        ),
        migrations.AddField(
            model_name='empapprovedetail',
            name='primary_emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_emp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empapprovedetail',
            name='secondary_emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_emp', to=settings.AUTH_USER_MODEL),
        ),
    ]
