# Generated by Django 2.0.5 on 2018-06-14 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('states', '0001_initial'),
        ('departments', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=255)),
                ('dob', models.DateTimeField()),
                ('alt_contact', models.CharField(max_length=255)),
                ('pan', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=100, null=True)),
                ('adhaar_no', models.CharField(blank=True, max_length=100, null=True)),
                ('epf_status', models.BooleanField(default=False)),
                ('epf_no', models.CharField(max_length=100)),
                ('emp_present_address', models.CharField(max_length=255)),
                ('emp_present_city', models.CharField(max_length=100)),
                ('emp_present_pin', models.CharField(max_length=100)),
                ('emp_permanent_address', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_permanent_city', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_permanent_pin', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_created_by', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.Departments')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='designation.Designation')),
                ('emp_permanent_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_permanent_state', to='states.State')),
                ('emp_present_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_present_state', to='states.State')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
