# Generated by Django 2.0.5 on 2018-06-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproject',
            name='is_approve',
            field=models.CharField(choices=[('2', 'False'), ('1', 'True'), ('0', 'None')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='companyproject',
            name='is_finalised',
            field=models.CharField(choices=[('2', 'False'), ('1', 'True'), ('0', 'None')], default='0', max_length=1),
        ),
    ]
