# Generated by Django 2.0.5 on 2018-06-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproject',
            name='lattitude',
            field=models.CharField(default=22.032145446, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyproject',
            name='longitude',
            field=models.CharField(default=20.365478987, max_length=200),
            preserve_default=False,
        ),
    ]
