# Generated by Django 2.0.3 on 2018-05-08 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0006_auto_20180507_1514'),
        ('company', '0006_auto_20180507_1824'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company_branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_address', models.CharField(max_length=100)),
                ('storage_city', models.CharField(max_length=50)),
                ('storage_pincode', models.CharField(max_length=50)),
                ('storage_contact_no', models.BigIntegerField()),
                ('storage_email', models.EmailField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_branch.CompanyBranch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('storage_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='states.State')),
            ],
        ),
    ]
