# Generated by Django 2.0.5 on 2018-06-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_project', '0002_auto_20180607_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprojectdetail',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
