# Generated by Django 2.0.5 on 2018-06-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_project', '0002_auto_20180613_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproject',
            name='lattitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companyproject',
            name='longitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
