# Generated by Django 2.0.3 on 2018-05-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_branch', '0003_auto_20180508_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagebin',
            name='bin_volume',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
