# Generated by Django 2.0.3 on 2018-05-09 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_branch', '0004_auto_20180508_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybranch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_branch', to='company.Company'),
        ),
    ]
