# Generated by Django 2.0.3 on 2018-05-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_branch', '0005_auto_20180509_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybranch',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storagebin',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
