# Generated by Django 2.0.5 on 2018-06-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
