# Generated by Django 2.0.5 on 2018-06-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_master', '0003_auto_20180607_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtype',
            name='margin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
