# Generated by Django 2.0.5 on 2018-06-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_master', '0004_materialtype_margin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialtype',
            name='margin',
        ),
        migrations.AddField(
            model_name='material',
            name='margin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
