# Generated by Django 2.0.5 on 2018-06-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requisition', '0003_auto_20180615_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='approval_level',
            field=models.IntegerField(default='0'),
        ),
    ]
