# Generated by Django 2.0.5 on 2018-06-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requisition', '0004_requisition_approval_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisition',
            options={},
        ),
    ]
