# Generated by Django 2.0.5 on 2018-06-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailtemplate',
            old_name='content',
            new_name='html_content',
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='text_content',
            field=models.TextField(default='dfghdfg'),
            preserve_default=False,
        ),
    ]
