# Generated by Django 2.0.5 on 2018-06-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20180626_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplate',
            name='code',
            field=models.CharField(default='bhj', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='subject',
            field=models.CharField(default='subject', max_length=255),
            preserve_default=False,
        ),
    ]
