# Generated by Django 2.0.3 on 2018-05-16 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_order', '0007_auto_20180515_1906'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendor', '0003_auto_20180515_1409'),
        ('company', '0008_auto_20180514_1542'),
        ('purchaseorggroup', '0003_auto_20180509_1712'),
        ('grn', '0004_auto_20180516_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_gst', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_approve', models.CharField(choices=[('2', 'False'), ('1', 'True'), ('0', 'None')], default='0', max_length=1)),
                ('is_finalised', models.CharField(choices=[('2', 'False'), ('1', 'True'), ('0', 'None')], default='0', max_length=1)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grn.GRN')),
                ('po_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_order.PurchaseOrder')),
                ('pur_grp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchaseorggroup.PurchaseGroup')),
                ('pur_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchaseorggroup.PurchaseOrg')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.Vendor')),
                ('vendor_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.VendorAddress')),
            ],
        ),
    ]
