# Generated by Django 2.0.5 on 2018-06-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='po_order',
        ),
    ]
