# Generated by Django 2.0.3 on 2018-05-16 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material_master', '0002_material_is_sales'),
        ('purchase_invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_per', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_amount_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_master.Material')),
                ('pur_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pur_invoice', to='purchase_invoice.PurchaseInvoice')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_inv_no', models.CharField(max_length=255)),
                ('pur_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pur_invoice_map', to='purchase_invoice.PurchaseInvoice')),
            ],
        ),
    ]
