# Generated by Django 2.0.5 on 2018-06-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_invoice', '0002_remove_purchaseinvoice_po_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='approval_level',
            field=models.IntegerField(default='0'),
        ),
    ]
